// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abcgztitbftfrxfdiwbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiY2d6dGl0YmZ0ZnJ4ZmRpd2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTM1MjksImV4cCI6MjA2NTk4OTUyOX0.uviCECX4yX28CmxSv8ZTiM1H5MS1f4os7w1_6Qc_q1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);